spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:hsqldb:file:./itbooksdb;DB_CLOSE_ON_EXIT=FALSE;hsqldb.lob_compressed=true
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect


  thymeleaf:
    check-template-location: true
    prefix: classpath:/WEB-INF/templates/
    suffix: .html
    servlet.content-type: text/html
    cache: false
    mode: HTML

  servlet:
    context-path: /
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

server:
  port: 8081

---

spring:
  profiles: test

  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;hsqldb.lob_compressed=true
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect
